### PR TITLE
Compiling with 8.0

### PR DESCRIPTION
**Pull request by bitemyapp**
/cc @mwotton

### CODE REVIEW

**Comment by bitemyapp** [comment]
screenshot from 2016-09-13 13-24-06

**Comment by mwotton** [comment]
cheers :)

**Comment by bitemyapp** [comment]
@mwotton Text's Data instance is broken because stuff that is in `Data.Text.Internal` _appears_ to be in `Data.Text`.

This is actually the first time I've seen `.Internal` fuck something up.

**Comment by mwotton** [comment]
huh, that's an interesting bug. Is Data.Text doing something wrong, and GHC doesn't catch it, then?

**Comment by bitemyapp** [comment]
@mwotton `pack` lives in `Data.Text`, the namespaced reference to the type constructor is `Data.Text.Text`, but the data constructors for `Text` _actually_ live in `Data.Text.Internal`, which I think leads it astray.

I'm not sure how to assign fault here, `Text`'s `Data` instance appeared to do everything it was supposed to.

Cf. https://github.com/bos/text/blob/28631f0a212dec18f976524ddeb7105adf6a9ff7/Data/Text.hs#L390-L408

**Comment by mwotton** [comment]
Interesting. I know the bytestring instance is far less useful - most of them just call out to error :/

**Pull request merged**
